version: "3.1"
# https://docs.docker.com/compose/compose-file/

services:
  face-be:
    build: .
    container_name: face_be
    ports:
      - "8080:9000"
    networks:
      - face-network
      - jhub-network

volumes:
  core-dev-data:

networks:
  face-network:
    name: face-network
  jhub-network:
    name: jhub-network
    external: true