spring:
  profiles:
    active:
      - local_dev
  datasource:
    url: jdbc:mysql://face_mysql:3306/template?allowPublicKeyRetrieval=TRUE&useSSL=FALSE&createDatabaseIfNotExist=TRUE
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1a2b3c4d
  messages:
    basename: message
    encoding: UTF-8
    fallback-to-system-locale=: true
logging:
  level:
    org:
      springframework: info
server:
  port: 9000
application:
  face:
    env: "build"
  core:
    url: "core_be"
    port: "8000"