spring:
  profiles:
    active:
      - local_dev
  messages:
    basename: message
    encoding: UTF-8
    fallback-to-system-locale=: true
logging:
  level:
    org:
      springframework: info
server:
  port: 9000
application:
  face:
    env: "build"
  core:
    url: "core_be"
    port: "8000"